name: Ruff Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ruff:
    name: Run Ruff Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13.7"

      - name: Install Ruff
        run: |
          pip install ruff

      - name: Run Ruff lint check
        run: |
          ruff check .
